### ISSUE TITLE
initial feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/technobiz#1]
1)       Please use Trend Micro,Kaspersky,Hardware & firewalls(CISCO & FortiNet) & web development & social media services in slides on home page.

2)       In contact us please remove female picture & replace it with telephone or any other suitable gadget.

3)       Add Fahim Bhai’s Mobile no in contact us & my name & number as well.

4)       In “Partners” replace INTEL with CISCO & Fortinet respectively & bring them before DELL & HP.

5)       Also please make TechnoBiz logo more prominent by increasing its size suitably, we will provide you the logo.

**Comment by mubashir633** [comment]
1) Please use Trend Micro,Kaspersky,Hardware & firewalls(CISCO & FortiNet) & web development & social media services in slides on home page.(NOT FIXED)
This task is not related to my work.

2) In contact us please remove female picture & replace it with telephone or any other suitable gadget. ( Fixed)

3) Add Fahim Bhai’s Mobile no in contact us & my name & number as well. ( Fixed)

4) In “Partners” replace INTEL with CISCO & Fortinet respectively & bring them before DELL & HP. 
( Fixed)

5) Also please make TechnoBiz logo more prominent by increasing its size suitably, we will provide you the logo.( Fixed)
